name: Update pre-commit

on:
  # first of every month at midnight
  schedule:
    - cron: '0 0 1 * *'
  # on demand
  workflow_dispatch:

jobs:
  update:
    name: Update pre-commit hooks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up TorchTS
        id: setup
        uses: ./.github/actions/setup-torchts

      - name: Restore pre-commit cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ steps.setup.outputs.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Update pre-commit hooks
        run: poetry run pre-commit autoupdate

      - name: Get commit message and pull request body
        id: messages
        run: |
          DIFF=$(git diff --unified=1 |               # get one line around each change to include repos
            grep -E 'repo:|rev:' |                    # find lines with repo URLs and current/updated revs
            sed 's|.*com/||; s/.*rev: //' |           # isolate hook user/repo and rev numbers
            sed 'N;s/\n/: /; N;s/\n/ → /; s/^/- /')   # format changes as '- user/repo: old rev → new rev'
          DIFF="${DIFF//'%'/'%25'}"
          DIFF="${DIFF//$'\n'/'%0A'}"
          DIFF="${DIFF//$'\r'/'%0D'}"
          echo "::set-output name=pr_body::$DIFF"
          echo "::set-output name=commit_message::Update pre-commit hooks%0A%0A$DIFF"

      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1.3.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create pull request
        if: success()
        uses: peter-evans/create-pull-request@v3.11.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: ${{ steps.messages.outputs.commit_message }}
          committer: GitHub <noreply@github.com>
          author: torchts-bot[bot] <88511308+torchts-bot[bot]@users.noreply.github.com>
          base: main
          branch: pre-commit/update-hooks
          delete-branch: true
          title: Update pre-commit hooks
          body: ${{ steps.messages.outputs.pr_body }}
          labels: |
            dependencies
            pre-commit
